import type { Metadata } from 'next';
import { FileBarChart } from 'lucide-react';
import { requireSession } from '@/lib/auth';
import { getMonthlyRecap } from '@/lib/queries/reports';
import { getOrganizationPlanContext } from '@/lib/queries/organizations';
import { getLocalParts, pad2 } from '@/lib/tz';
import { idParam } from '@/lib/validators/common';
import Card from '@/components/ui/Card';
import Table from '@/components/ui/Table';
import BarList from '@/components/shared/BarList';
import DonutChart from '@/components/shared/DonutChart';
import EmptyState from '@/components/shared/EmptyState';
import ExportButtons from './export-buttons';

export const metadata: Metadata = { title: 'Laporan' };

const MONTH_PATTERN = /^\d{4}-\d{2}$/;

interface ReportsPageProps {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}

function firstValue(value: string | string[] | undefined): string | undefined {
  return Array.isArray(value) ? value[0] : value;
}

/** "YYYY-MM" for right now, in the org's default display timezone (TRD.md §14/organizations.timezone default). */
function currentMonthJakarta(): string {
  const { year, month } = getLocalParts(new Date(), 'Asia/Jakarta');
  return `${year}-${pad2(month)}`;
}

/**
 * Monthly recap (PRD.md US-05, TRD.md §6/§13 `GET /api/reports/monthly`). Server
 * Component, OWNER/ADMIN only: calls lib/queries/reports + lib/queries/organizations
 * directly (TRD.md §5), never a self-fetch over /api/*. The actual XLSX/PDF bytes are
 * only ever generated by the real /api/reports/monthly/export route handler, which
 * ./export-buttons.tsx links to — this page only reads the on-screen recap plus the
 * org's export_pdf plan feature, to decide whether that link even renders.
 */
export default async function ReportsPage({ searchParams }: ReportsPageProps) {
  const { orgId } = await requireSession(['OWNER', 'ADMIN']);
  const params = await searchParams;

  const monthRaw = firstValue(params.month);
  const month = monthRaw && MONTH_PATTERN.test(monthRaw) ? monthRaw : currentMonthJakarta();

  const branchIdRaw = firstValue(params.branchId);
  const branchIdResult = branchIdRaw ? idParam.safeParse(branchIdRaw) : undefined;
  const branchId = branchIdResult?.success ? branchIdResult.data : undefined;

  const [recap, org] = await Promise.all([
    getMonthlyRecap(orgId, { month, branchId }),
    getOrganizationPlanContext(orgId),
  ]);

  const canExportPdf = org?.features.export_pdf ?? false;

  const totals = recap.reduce(
    (acc, row) => ({
      present: acc.present + row.presentCount,
      late: acc.late + row.lateCount,
      absent: acc.absent + row.absentCount,
      leaveSickPermit: acc.leaveSickPermit + row.leaveCount + row.sickCount + row.permitCount,
    }),
    { present: 0, late: 0, absent: 0, leaveSickPermit: 0 },
  );
  const topLate = recap
    .filter((row) => row.totalLateMinutes > 0)
    .sort((a, b) => b.totalLateMinutes - a.totalLateMinutes)
    .slice(0, 5)
    .map((row) => ({ label: row.name, value: row.totalLateMinutes }));

  return (
    <div className="flex flex-col gap-4">
      <div>
        <h1 className="text-xl font-semibold text-text">Laporan</h1>
        <p className="text-sm text-muted">Rekap kehadiran bulanan per karyawan.</p>
      </div>

      <ExportButtons
        month={month}
        branchId={branchId !== undefined ? String(branchId) : undefined}
        canExportPdf={canExportPdf}
      />

      {recap.length === 0 ? (
        <EmptyState icon={FileBarChart} message="Belum ada data untuk bulan ini." />
      ) : (
        <>
          <div className="grid gap-4 lg:grid-cols-2">
            <Card shadow>
              <Card.Header>
                <h2 className="text-sm font-semibold text-text">Ringkasan Bulan Ini</h2>
              </Card.Header>
              <Card.Body>
                <DonutChart
                  centerValue={String(totals.present + totals.late)}
                  centerLabel="Hari Hadir"
                  segments={[
                    { label: 'Tepat Waktu', value: totals.present, color: 'var(--color-status-present)' },
                    { label: 'Terlambat', value: totals.late, color: 'var(--color-status-late)' },
                    { label: 'Tidak Hadir', value: totals.absent, color: 'var(--color-status-absent)' },
                    { label: 'Cuti/Sakit/Izin', value: totals.leaveSickPermit, color: 'var(--color-status-leave)' },
                  ]}
                />
              </Card.Body>
            </Card>

            <Card shadow>
              <Card.Header>
                <h2 className="text-sm font-semibold text-text">Keterlambatan Terbanyak</h2>
              </Card.Header>
              <Card.Body>
                {topLate.length === 0 ? (
                  <p className="text-sm text-muted">Tidak ada keterlambatan bulan ini.</p>
                ) : (
                  <BarList items={topLate} formatValue={(v) => `${v}m`} />
                )}
              </Card.Body>
            </Card>
          </div>

          <Table>
          <Table.Head>
            <Table.Row>
              <Table.HeadCell>Nama</Table.HeadCell>
              <Table.HeadCell>Cabang</Table.HeadCell>
              <Table.HeadCell>Hadir</Table.HeadCell>
              <Table.HeadCell>Terlambat</Table.HeadCell>
              <Table.HeadCell>Tidak Hadir</Table.HeadCell>
              <Table.HeadCell>Cuti</Table.HeadCell>
              <Table.HeadCell>Sakit</Table.HeadCell>
              <Table.HeadCell>Izin</Table.HeadCell>
              <Table.HeadCell>Total Menit Terlambat</Table.HeadCell>
              <Table.HeadCell>Total Jam Kerja</Table.HeadCell>
            </Table.Row>
          </Table.Head>
          <Table.Body>
            {recap.map((row) => (
              <Table.Row key={row.userId}>
                <Table.Cell>{row.name}</Table.Cell>
                <Table.Cell>{row.branchName ?? '-'}</Table.Cell>
                <Table.Cell>{row.presentCount}</Table.Cell>
                <Table.Cell>{row.lateCount}</Table.Cell>
                <Table.Cell>{row.absentCount}</Table.Cell>
                <Table.Cell>{row.leaveCount}</Table.Cell>
                <Table.Cell>{row.sickCount}</Table.Cell>
                <Table.Cell>{row.permitCount}</Table.Cell>
                <Table.Cell>{row.totalLateMinutes}</Table.Cell>
                <Table.Cell>{(row.totalWorkMinutes / 60).toFixed(1)}</Table.Cell>
              </Table.Row>
            ))}
          </Table.Body>
          </Table>
        </>
      )}
    </div>
  );
}
